require("user.functions")
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.autocommands")
require("user.commands")

require("user.autopairs")
require("user.cmp")
require("user.comment")
require("user.gitsigns")
require("user.fidget")
require("user.illuminate")
require("user.indentline")
require("user.lualine")
require("user.nvim-tree")
require("user.project")
require("user.telescope")
require("user.toggleterm")
require("user.treesitter")
require("user.whichkey")

require("user.lsp")
